Signed score diffs
byu-dml/d3m-mtl-db-reader pull request #13
Opened 2019-10-25 23:25 UTC by JeremyRees

Resolves #10. The issue itself is solved in the first commit, [Don't take absolute value of score diffs](https://github.com/byu-dml/d3m-mtl-db-reader/commit/dffeb4680a88f1017c7e36c8cfb4afb27f32e6b7).

The rest of the pull request is the creation of unit tests to check the correct ordering of everything in the primitive pair aggregation. Along with this I added tests for pipeline run entities and other tests for the primitive pair aggregation. Because pipeline runs reference pipelines, datasets, problems, and predictions, I had to create a lot of new test data, which makes up the bulk of this PR.

The commit [Allow specifying run predictions path](https://github.com/byu-dml/d3m-mtl-db-reader/commit/c06aa156ca5803e43bf4fdc900ac40925410f55e) was necessary because previously the `PipelineRun` entity was hard-coded to find predictions under the `DATA_ROOT` directory, but we needed to change that for our unit tests. To maintain consistency, `**kwargs` was also added to the constructor for `Dataset`s, `Pipeline`s, and `Problem`s.

2019-10-28 18:15 UTC, epeters3 commented on src/aggregations/primitive_pairs.py
> +    """
Beautiful documentation.

2019-10-28 18:20 UTC, epeters3 commented on src/aggregations/primitive_pairs.py
> +    """
It looks like down below on line 181 the actual computation is `run_b_score.value - run_a_score.value`.

2019-10-28 18:21 UTC, epeters3 commented on src/entities/pipeline_run.py
> +        self.pipeline: Union[DocumentReference, Pipeline] = DocumentReference(
Good catch.

2019-10-28 18:25 UTC, epeters3 commented on src/entities/pipeline_run.py
> +    def init_predictions(self, pipeline_run_dict, **kwargs) -> None:
I think the more common convention is to document all used parameters in the function signature. Maybe we could change the function signature to something like `def init_predictions(self, pipeline_run_dict, *, run_predictions_path = DataDir.PREDICTIONS_DUMP.value, **kwargs) -> None:`

2019-10-28 18:25 UTC, epeters3 commented on src/entities/pipeline_run.py
> +    def init_predictions(self, pipeline_run_dict, **kwargs) -> None:
Then we wouldn't need the `kwargs.get(...)` call.

2019-10-28 19:07 UTC, epeters3 commented on tests/utils.py
> +            'invalid_pipeline_run_d', # Problem task type is unsupported
This documentation of what each test data document contains and can be used for is great. Would you be willing to add a small comment like this to the similar pipeline runs and invalid problem as well?

2019-10-28 19:09 UTC, epeters3 requested changes
This is beautiful Jeremy. I appreciate you describing the test data you added, and the unit tests are so nice to have. Please see my comments on this PR.

2019-10-28 19:09 UTC, epeters3 requested changes
This is beautiful Jeremy. I appreciate you describing the test data you added, and the unit tests are so nice to have. Please see my comments on this PR.

2019-10-30 16:25 UTC, JeremyRees commented on src/aggregations/primitive_pairs.py
> +    """
Oops, good catch!

2019-10-30 17:32 UTC, epeters3 approved these changes

2019-10-30 17:32 UTC, merged